const retailers={amazon:'Amazon',walmart:'Walmart',target:'Target',wayfair:'Wayfair',lowes:"Lowe's",homedepot:'Home Depot',bestbuy:'Best Buy'};
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/analyze'&&request.method==='POST'){try{return json(await analyze(await request.json()),200)}catch(error){return json({error:error.message||'Unable to analyze this item.'},400)}}if(url.pathname.startsWith('/api/'))return json({error:'Not found'},404);return env.ASSETS.fetch(request)}};
async function analyze(body){const input=String(body?.query||body?.url||'').trim();if(!input)throw new Error('Add a product link or product name.');let title=input,sourceStore='',sourceUrl='',listedPrice=null,dimensions=null,risks=[];if(/^https?:\/\//i.test(input)){const parsed=new URL(input);if(isPrivate(parsed.hostname))throw new Error('Private network links are not supported.');sourceUrl=parsed.href;sourceStore=storeName(parsed.hostname);try{const response=await fetch(parsed.href,{headers:{'user-agent':'Mozilla/5.0 ShouldIBuyThis/0.1'},redirect:'follow'});const html=(await response.text()).slice(0,900000);title=meta(html,'og:title')||title;listedPrice=number(meta(html,'product:price:amount'))||findPrice(html);dimensions=findDimensions(strip(html));if(!response.ok)risks.push({level:'medium',text:`The source retailer returned HTTP ${response.status}. Confirm details at checkout.`})}catch{risks.push({level:'medium',text:'The source listing could not be fully verified. Confirm the current price and delivery at checkout.'})}}else{listedPrice=findPrice(input);dimensions=findDimensions(input)}
const base=listedPrice||99;const stores=[sourceStore||'Source retailer','Walmart','Target'];const offers=stores.map((store,index)=>({store,price:round(base*(index===0?1:index===1?.96:1.04)),shipping:index===1?9.99:0,arrival:index===2?'Fastest public estimate':'Confirm at checkout',match:index===0?'Exact':index===1?'Likely':'Similar',risk:index===0?'low':'medium',url:index===0?sourceUrl:''}));if(!listedPrice)risks.push({level:'medium',text:'A reliable public price was not found, so comparison prices are placeholders for interface testing.'});if(!dimensions)risks.push({level:'low',text:'No dimensions were verified. Add measurements when fit matters.'});return{researchMode:listedPrice?'partial':'demo',product:{title:clean(title),category:dimensions?'Furniture or sized item':'General',dimensions,sourceStore,sourceUrl,listedPrice},offers,risks,summary:listedPrice?'The source price was found; shipping and alternate-retailer offers still require verification.':'The product was identified, but live cross-retailer data is not connected yet.'}}
function json(data,status){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function meta(html,property){const escaped=property.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const pattern of [new RegExp(`<meta[^>]+property=["']${escaped}["'][^>]+content=["']([^"']+)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+property=["']${escaped}["']`,'i')]){const found=html.match(pattern);if(found)return found[1]}return''}
function findPrice(text=''){const found=String(text).match(/(?:US\$|\$)\s?([1-9]\d{0,5}(?:,\d{3})*(?:\.\d{2})?)/);return found?Number(found[1].replace(/,/g,'')):null}
function findDimensions(text=''){const found=String(text).match(/(\d+(?:\.\d+)?)\s*(?:in(?:ches?)?|\")?\s*[wW]?\s*[x×]\s*(\d+(?:\.\d+)?)\s*(?:in(?:ches?)?|\")?/);return found?{width:Number(found[1]),depth:Number(found[2])}:null}
function storeName(host){const key=Object.keys(retailers).find(k=>host.toLowerCase().includes(k));return key?retailers[key]:host.replace(/^www\./,'')}
function strip(value=''){return value.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')}
function clean(value=''){return String(value).replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim().slice(0,180)}
function number(value){const n=Number(String(value||'').replace(/[^\d.]/g,''));return Number.isFinite(n)&&n>0?n:null}
function round(value){return Math.round(value*100)/100}
function isPrivate(host){return host==='localhost'||/^(10\.|127\.|169\.254\.|192\.168\.)/.test(host)||/^172\.(1[6-9]|2\d|3[01])\./.test(host)}
